# Generated by Django 5.2.3 on 2025-06-10 15:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_Hotel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('catindex', models.IntegerField(default=0)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='fecilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='updateddate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.category'),
        ),
    ]
