# Generated by Django 5.2.3 on 2025-06-10 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_category_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='HotelCategory',
        ),
        migrations.RenameField(
            model_name='hotelcategory',
            old_name='catindex',
            new_name='cat_index',
        ),
        migrations.RenameField(
            model_name='hotelcategory',
            old_name='createddate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='hotelcategory',
            old_name='updateddate',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='hoteldetail',
            old_name='addressline1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='hoteldetail',
            old_name='addressline2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='hoteldetail',
            old_name='shortid',
            new_name='short_id',
        ),
        migrations.RenameField(
            model_name='hoteldetail',
            old_name='updateddate',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='hoteldetail',
            name='createddate',
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
